SELECT ?property ?propertyLabel ?type (COUNT(?s) AS ?cnt) WITH {{
  SELECT DISTINCT ?item WHERE {{
    SERVICE wikibase:mwapi {{
      bd:serviceParam wikibase:api 'Generator'; wikibase:endpoint 'www.wikidata.org'; mwapi:generator 'links'; mwapi:titles '{pagetitle}' .
      ?title wikibase:apiOutput mwapi:title  .
      ?ns wikibase:apiOutput '@ns' .
      ?pageId wikibase:apiOutput mwapi:pageid .
    }}
    FILTER(BOUND(?pageId)) .
    FILTER(STR(?ns) = '0') .
    BIND(IRI(CONCAT(STR(wd:), ?title)) AS ?item) .
  }}
}} AS %subquery1 WITH {{
  SELECT ?p ?s WHERE {{
    INCLUDE %subquery1 .
    ?item ?p ?s .
  }}
}} AS %subquery2 WHERE {{
  INCLUDE %subquery2 .
  ?property wikibase:claim ?p; wikibase:propertyType ?type .
  FILTER(?type != wikibase:ExternalId) .
  SERVICE wikibase:label {{ bd:serviceParam wikibase:language 'en' }}
}} GROUP BY ?property ?propertyLabel ?type ORDER BY DESC(?cnt)